### PR TITLE
Split into array

### PR DESCRIPTION
**Pull request by jacobkim9881**
We are agreed with the fact that users could edit language list of `./src/lang_code.js` by any mistakes. To add languages to translate users should add values in `langsToTranslate` array at `./src/lang_code.js` in `improve-language-selector` branch. I made js file to import the array in my branch `split-into-array`. So users can add values to add languages or leave it to add all languages to translate. Please to check this pull request. No errors after testing the repo.

If the branch `improve-language-selector` is pulled to `master` branch, [The guidance](https://github.com/jacobkim9881/localization-manager/tree/split-into-array#localization-manager) will not be useful as a guide. Added [an issue about this](https://github.com/jacobkim9881/localization-manager/issues/9). <s> By this commits the guide document should leads users to `./src/edit-lang-coverage.js` not `./src/lang_code.js`. </s> 

The first issue is [#5 from jacobkim9881's repo](https://github.com/jacobkim9881/localization-manager/issues/5). And then the issues solution is [this branch](https://github.com/TeaBizzy/localization-manager/tree/improve-language-selector) and the pull request of the branch is [here](https://github.com/jacobkim9881/localization-manager/pull/7).

### CODE REVIEW

**Comment by TeaBizzy** [comment]
@jacobkim9881 sorry I missed this. I will take a look in the morning. But I agree with the idea to seperate these and from my inital look at the PR it looks good.

**Review by TeaBizzy — COMMENTED** [review]
Hi @jacobkim9881, I think in order to isolate the `languageToTranslate` array and the  `langsExplain` object it would make more sense to have just the `langExplain` object in its own file, and export it to the `src/edit-lang-coverage.js` to be used. The logic at line 118 in `src/lang_code.js` can then be moved to `src/edit-lang-coverage.js`.

Looking at  the comments in `src/edit-lang-coverage.js`, does the key (af, yi, xh) work, the keys value ("Afrikaans", "Yiddish", "Xhosa"), or do both of them work?

IMO it would be simpler to just grab the values directly from the required object `langsExplain.af`, this would prevent the user from worrying about spelling issues, and eliminate the comments currently in `src/edit-lang-coverage.js`.

Let me know your thoughts.

**Comment by jacobkim9881** [comment]
@TeaBizzy Please to review the pull request and double check. At my end there is no error and works well. Would be happy if without any issues.

**Comment by TeaBizzy** [comment]
@jacobkim9881, see my review above, let me know what you think :smiley:

**Comment by jacobkim9881** [comment]
Please to check my reply and review the [added commits](https://github.com/TeaBizzy/localization-manager/pull/1/commits/adb7e46acde8ac170ae08605e53648bf82e2ea63).

> Looking at the comments in src/edit-lang-coverage.js, does the key (af, yi, xh) work, the keys value ("Afrikaans", "Yiddish", "Xhosa"), or do both of them work?

The repository works with keys (af, yi, xh) without keys value ("Afrikaans", "Yiddish", "Xhosa"). Google translate API needs such keys to translate. Such keys value are just for explaining what keys meaning its country. So when exporting `langsExplain` object `src/edit-lang-coverage.js` in the repository and when exporting it at line 3 in `src/.index.js`, only keys are needed for executing the repository.

Seems much better for reading code. Please to check and review the code and if any edits are needed then let me know to fix!

**Review by TeaBizzy — APPROVED** [review]

**Comment by TeaBizzy** [comment]
@jacobkim9881 These changes look good to me. The end user should now be able to choose which languages to translate to with no guess work. The comments have been made cleaner and are easier to read.

Seeing as this will merge on my fork of the repo do I open a PR to the main repo, or can you merge it yourself?

Cheers! :clinking_glasses:

**Comment by jacobkim9881** [comment]
@TeaBizzy Thanks for the review! I will merge this branch by myself into the master branch.

**Pull request merged**
